---
sudo: required
services:
  - docker
language: php
php:
  - 7.1
env:
  - WP_ENV=testing
before_install:
  - docker-compose -v
  - docker -v
install:
before_script:
script:
  - sudo -E docker-compose -f docker-compose.yml run ci
after_script:
  - docker ps -a
  - docker-compose logs

